codeDir="$projectRoot/app/code"
designDir="$projectRoot/app/dir"
vendorDir="$projectRoot/vendor"

# project var dir, sub directory for qa cache files and output files
varDir="$projectRoot/var/qa";

cacheDir="$projectRoot/cache/qa";

# the path in this library for default config
defaultConfigPath="$(readlink -f $DIR/../configDefaults/)"

# PHPStan configs
phpstanConfigPath="$(configPath phpstan.neon)"

#PHP Mess Detector Configs
phpmdConfigPath="$projectRoot/dev/tests/static/testsuite/Magento/Test/Php/_files/phpmd/ruleset.xml"

# coding Standard for checking
# checks for a folder called 'condingStandards' in the $projectConfigPath, falls back to the PSR2 standards
phpcsCodingStandardsPath="$projectRoot/vendor/magento/marketplace-eqp/MEQP2/"

# should coding standards warnings be a fail?
phpcsFailOnWarning=0

##PHPUnit Configs

# PHPUnit Quick Tests - optional skip slow tests
phpUnitQuickTests=${phpUnitQuickTests:-1}

# PHPUnit Coverage - if enabled, tests will run with Xdebug and generate coverage
phpUnitCoverage=${phpUnitCoverage:-1}

if [[ -f $projectRoot/dev/tests/unit/phpunit.xml ]]
then
    # Project root phpunit.xml trumps everything else
    phpUnitConfigPath=$projectRoot/dev/tests/unit/phpunit.xml
elif [[ -f $projectRoot/dev/tests/unit/phpunit.xml.dist ]]
then
    # Project root phpunit.xml trumps everything else
    phpUnitConfigPath=$projectRoot/dev/tests/unit/phpunit.xml.dist
else
    echo "No PHPUnit config was found at either:"
    echo "- $projectRoot/dev/tests/unit/phpunit.xml"
    echo "- $projectRoot/dev/tests/unit/phpunit.xml.dist"
fi

pathsToCheck=();

if [[ -d "$projectRoot/app/code" ]]
then
    pathsToCheck[]="$projectRoot/app/code"
fi
if [[ -d "$projectRoot/app/design" ]]
then
    pathsToCheck[]="$projectRoot/app/design"
fi
if [[ -d "$projectRoot/vendor" ]]
then
    pathsToCheck[]="$projectRoot/vendor"
fi




pathsToIgnore=();

# To renew this list, navigate to a Magento2 that only has phpqa installed, cd to the vendor folder and run:
# find . -maxdepth 2 -type d | grep -P "/.*/" | sed "s#./#\$pathsToIgnore[]=\"vendor/#" | sed "s#\$#\"#"
$pathsToCheck[]="/vendor/magento/language-zh_hans_cn"
$pathsToCheck[]="/vendor/magento/language-pt_br"
$pathsToCheck[]="/vendor/magento/language-nl_nl"
$pathsToCheck[]="/vendor/magento/language-fr_fr"
$pathsToCheck[]="/vendor/magento/language-es_es"
$pathsToCheck[]="/vendor/magento/language-en_us"
$pathsToCheck[]="/vendor/magento/language-de_de"
$pathsToCheck[]="/vendor/magento/module-require-js"
$pathsToCheck[]="/vendor/magento/module-media-storage"
$pathsToCheck[]="/vendor/magento/module-developer"
$pathsToCheck[]="/vendor/magento/module-cms-url-rewrite"
$pathsToCheck[]="/vendor/magento/module-authorization"
$pathsToCheck[]="/vendor/magento/module-security"
$pathsToCheck[]="/vendor/magento/module-rule"
$pathsToCheck[]="/vendor/magento/module-msrp"
$pathsToCheck[]="/vendor/magento/module-gift-message"
$pathsToCheck[]="/vendor/magento/module-sales-sequence"
$pathsToCheck[]="/vendor/magento/module-product-alert"
$pathsToCheck[]="/vendor/magento/module-rss"
$pathsToCheck[]="/vendor/magento/module-weee"
$pathsToCheck[]="/vendor/magento/module-webapi-security"
$pathsToCheck[]="/vendor/magento/module-version"
$pathsToCheck[]="/vendor/magento/module-usps"
$pathsToCheck[]="/vendor/magento/module-tax-import-export"
$pathsToCheck[]="/vendor/magento/module-swatches-layered-navigation"
$pathsToCheck[]="/vendor/magento/module-swagger"
$pathsToCheck[]="/vendor/magento/module-robots"
$pathsToCheck[]="/vendor/magento/module-signifyd"
$pathsToCheck[]="/vendor/magento/module-send-friend"
$pathsToCheck[]="/vendor/magento/module-sales-inventory"
$pathsToCheck[]="/vendor/magento/module-persistent"
$pathsToCheck[]="/vendor/magento/module-offline-payments"
$pathsToCheck[]="/vendor/magento/module-multishipping"
$pathsToCheck[]="/vendor/magento/module-layered-navigation"
$pathsToCheck[]="/vendor/magento/module-grouped-import-export"
$pathsToCheck[]="/vendor/magento/module-cookie"
$pathsToCheck[]="/vendor/magento/module-google-analytics"
$pathsToCheck[]="/vendor/magento/module-google-adwords"
$pathsToCheck[]="/vendor/magento/module-fedex"
$pathsToCheck[]="/vendor/magento/module-encryption-key"
$pathsToCheck[]="/vendor/magento/module-downloadable-import-export"
$pathsToCheck[]="/vendor/magento/module-dhl"
$pathsToCheck[]="/vendor/magento/module-currency-symbol"
$pathsToCheck[]="/vendor/magento/module-configurable-product-sales"
$pathsToCheck[]="/vendor/magento/module-configurable-import-export"
$pathsToCheck[]="/vendor/magento/module-checkout-agreements"
$pathsToCheck[]="/vendor/magento/module-catalog-widget"
$pathsToCheck[]="/vendor/magento/module-catalog-rule-configurable"
$pathsToCheck[]="/vendor/magento/module-captcha"
$pathsToCheck[]="/vendor/magento/module-cache-invalidate"
$pathsToCheck[]="/vendor/magento/module-bundle-import-export"
$pathsToCheck[]="/vendor/magento/module-authorizenet"
$pathsToCheck[]="/vendor/magento/module-advanced-pricing-import-export"
$pathsToCheck[]="/vendor/magento/module-marketplace"
$pathsToCheck[]="/vendor/magento/composer"
$pathsToCheck[]="/vendor/magento/zendframework1"
$pathsToCheck[]="/vendor/magento/data-migration-tool"
$pathsToCheck[]="/vendor/magento/magento-composer-installer"
$pathsToCheck[]="/vendor/magento/framework"
$pathsToCheck[]="/vendor/magento/module-config"
$pathsToCheck[]="/vendor/magento/module-deploy"
$pathsToCheck[]="/vendor/magento/module-store"
$pathsToCheck[]="/vendor/magento/module-ui"
$pathsToCheck[]="/vendor/magento/module-user"
$pathsToCheck[]="/vendor/magento/module-email"
$pathsToCheck[]="/vendor/magento/module-variable"
$pathsToCheck[]="/vendor/magento/module-backend"
$pathsToCheck[]="/vendor/magento/module-translation"
$pathsToCheck[]="/vendor/magento/module-quote"
$pathsToCheck[]="/vendor/magento/module-catalog-inventory"
$pathsToCheck[]="/vendor/magento/module-page-cache"
$pathsToCheck[]="/vendor/magento/module-widget"
$pathsToCheck[]="/vendor/magento/module-theme"
$pathsToCheck[]="/vendor/magento/module-eav"
$pathsToCheck[]="/vendor/magento/module-catalog"
$pathsToCheck[]="/vendor/magento/module-url-rewrite"
$pathsToCheck[]="/vendor/magento/module-catalog-url-rewrite"
$pathsToCheck[]="/vendor/magento/module-cms"
$pathsToCheck[]="/vendor/magento/module-sales"
$pathsToCheck[]="/vendor/magento/module-customer"
$pathsToCheck[]="/vendor/magento/module-integration"
$pathsToCheck[]="/vendor/magento/module-wishlist"
$pathsToCheck[]="/vendor/magento/module-shipping"
$pathsToCheck[]="/vendor/magento/module-tax"
$pathsToCheck[]="/vendor/magento/module-reports"
$pathsToCheck[]="/vendor/magento/module-sales-rule"
$pathsToCheck[]="/vendor/magento/module-catalog-rule"
$pathsToCheck[]="/vendor/magento/module-directory"
$pathsToCheck[]="/vendor/magento/module-grouped-product"
$pathsToCheck[]="/vendor/magento/module-checkout"
$pathsToCheck[]="/vendor/magento/module-payment"
$pathsToCheck[]="/vendor/magento/module-downloadable"
$pathsToCheck[]="/vendor/magento/module-contact"
$pathsToCheck[]="/vendor/magento/module-newsletter"
$pathsToCheck[]="/vendor/magento/module-review"
$pathsToCheck[]="/vendor/magento/module-indexer"
$pathsToCheck[]="/vendor/magento/module-import-export"
$pathsToCheck[]="/vendor/magento/module-catalog-import-export"
$pathsToCheck[]="/vendor/magento/module-cron"
$pathsToCheck[]="/vendor/magento/module-backup"
$pathsToCheck[]="/vendor/magento/theme-frontend-blank"
$pathsToCheck[]="/vendor/magento/theme-frontend-luma"
$pathsToCheck[]="/vendor/magento/theme-adminhtml-backend"
$pathsToCheck[]="/vendor/magento/module-wishlist-analytics"
$pathsToCheck[]="/vendor/magento/module-webapi"
$pathsToCheck[]="/vendor/magento/module-vault"
$pathsToCheck[]="/vendor/magento/module-ups"
$pathsToCheck[]="/vendor/magento/module-configurable-product"
$pathsToCheck[]="/vendor/magento/module-swatches"
$pathsToCheck[]="/vendor/magento/module-sitemap"
$pathsToCheck[]="/vendor/magento/module-search"
$pathsToCheck[]="/vendor/magento/module-catalog-search"
$pathsToCheck[]="/vendor/magento/module-sample-data"
$pathsToCheck[]="/vendor/magento/module-sales-analytics"
$pathsToCheck[]="/vendor/magento/module-review-analytics"
$pathsToCheck[]="/vendor/magento/module-release-notification"
$pathsToCheck[]="/vendor/magento/module-quote-analytics"
$pathsToCheck[]="/vendor/magento/module-product-video"
$pathsToCheck[]="/vendor/magento/module-instant-purchase"
$pathsToCheck[]="/vendor/magento/module-paypal"
$pathsToCheck[]="/vendor/magento/module-offline-shipping"
$pathsToCheck[]="/vendor/magento/module-new-relic-reporting"
$pathsToCheck[]="/vendor/magento/module-google-optimizer"
$pathsToCheck[]="/vendor/magento/module-customer-import-export"
$pathsToCheck[]="/vendor/magento/module-customer-analytics"
$pathsToCheck[]="/vendor/magento/module-catalog-analytics"
$pathsToCheck[]="/vendor/magento/module-bundle"
$pathsToCheck[]="/vendor/magento/module-braintree"
$pathsToCheck[]="/vendor/magento/module-analytics"
$pathsToCheck[]="/vendor/magento/module-admin-notification"
$pathsToCheck[]="/vendor/magento/magento2-base"
$pathsToCheck[]="/vendor/magento/marketplace-eqp"
$pathsToCheck[]="/vendor/composer/semver"
$pathsToCheck[]="/vendor/composer/composer"
$pathsToCheck[]="/vendor/composer/ca-bundle"
$pathsToCheck[]="/vendor/composer/spdx-licenses"
$pathsToCheck[]="/vendor/shopialfb/facebook-module"
$pathsToCheck[]="/vendor/zendframework/zend-stdlib"
$pathsToCheck[]="/vendor/zendframework/zend-hydrator"
$pathsToCheck[]="/vendor/zendframework/zend-escaper"
$pathsToCheck[]="/vendor/zendframework/zend-uri"
$pathsToCheck[]="/vendor/zendframework/zend-loader"
$pathsToCheck[]="/vendor/zendframework/zend-http"
$pathsToCheck[]="/vendor/zendframework/zend-filter"
$pathsToCheck[]="/vendor/zendframework/zend-math"
$pathsToCheck[]="/vendor/zendframework/zend-crypt"
$pathsToCheck[]="/vendor/zendframework/zend-code"
$pathsToCheck[]="/vendor/zendframework/zend-captcha"
$pathsToCheck[]="/vendor/zendframework/zend-log"
$pathsToCheck[]="/vendor/zendframework/zend-json"
$pathsToCheck[]="/vendor/zendframework/zend-di"
$pathsToCheck[]="/vendor/zendframework/zend-config"
$pathsToCheck[]="/vendor/zendframework/zend-i18n"
$pathsToCheck[]="/vendor/zendframework/zend-text"
$pathsToCheck[]="/vendor/zendframework/zend-server"
$pathsToCheck[]="/vendor/zendframework/zend-console"
$pathsToCheck[]="/vendor/zendframework/zend-db"
$pathsToCheck[]="/vendor/zendframework/zend-validator"
$pathsToCheck[]="/vendor/zendframework/zend-servicemanager"
$pathsToCheck[]="/vendor/zendframework/zend-inputfilter"
$pathsToCheck[]="/vendor/zendframework/zend-form"
$pathsToCheck[]="/vendor/zendframework/zend-eventmanager"
$pathsToCheck[]="/vendor/zendframework/zend-modulemanager"
$pathsToCheck[]="/vendor/zendframework/zend-serializer"
$pathsToCheck[]="/vendor/zendframework/zend-soap"
$pathsToCheck[]="/vendor/zendframework/zend-view"
$pathsToCheck[]="/vendor/zendframework/zend-psr7bridge"
$pathsToCheck[]="/vendor/zendframework/zend-mvc"
$pathsToCheck[]="/vendor/zendframework/zend-session"
$pathsToCheck[]="/vendor/zendframework/zend-diactoros"
$pathsToCheck[]="/vendor/psr/container"
$pathsToCheck[]="/vendor/psr/log"
$pathsToCheck[]="/vendor/psr/http-message"
$pathsToCheck[]="/vendor/container-interop/container-interop"
$pathsToCheck[]="/vendor/tedivm/jshrink"
$pathsToCheck[]="/vendor/symfony/debug"
$pathsToCheck[]="/vendor/symfony/polyfill-mbstring"
$pathsToCheck[]="/vendor/symfony/polyfill-php54"
$pathsToCheck[]="/vendor/symfony/polyfill-php55"
$pathsToCheck[]="/vendor/symfony/polyfill-php70"
$pathsToCheck[]="/vendor/symfony/polyfill-php72"
$pathsToCheck[]="/vendor/symfony/console"
$pathsToCheck[]="/vendor/symfony/event-dispatcher"
$pathsToCheck[]="/vendor/symfony/process"
$pathsToCheck[]="/vendor/symfony/filesystem"
$pathsToCheck[]="/vendor/symfony/config"
$pathsToCheck[]="/vendor/symfony/dependency-injection"
$pathsToCheck[]="/vendor/symfony/finder"
$pathsToCheck[]="/vendor/symfony/stopwatch"
$pathsToCheck[]="/vendor/oyejorge/less.php"
$pathsToCheck[]="/vendor/monolog/monolog"
$pathsToCheck[]="/vendor/seld/phar-utils"
$pathsToCheck[]="/vendor/seld/cli-prompt"
$pathsToCheck[]="/vendor/seld/jsonlint"
$pathsToCheck[]="/vendor/justinrainbow/json-schema"
$pathsToCheck[]="/vendor/colinmollenhour/credis"
$pathsToCheck[]="/vendor/colinmollenhour/php-redis-session-abstract"
$pathsToCheck[]="/vendor/colinmollenhour/cache-backend-file"
$pathsToCheck[]="/vendor/colinmollenhour/cache-backend-redis"
$pathsToCheck[]="/vendor/paragonie/random_compat"
$pathsToCheck[]="/vendor/braintree/braintree_php"
$pathsToCheck[]="/vendor/ramsey/uuid"
$pathsToCheck[]="/vendor/league/climate"
$pathsToCheck[]="/vendor/sjparkinson/static-review"
$pathsToCheck[]="/vendor/phpseclib/phpseclib"
$pathsToCheck[]="/vendor/tubalmartin/cssmin"
$pathsToCheck[]="/vendor/pelago/emogrifier"
$pathsToCheck[]="/vendor/squizlabs/php_codesniffer"
$pathsToCheck[]="/vendor/lusitanian/oauth"
$pathsToCheck[]="/vendor/theseer/fdomdocument"
$pathsToCheck[]="/vendor/theseer/tokenizer"
$pathsToCheck[]="/vendor/sebastian/version"
$pathsToCheck[]="/vendor/sebastian/resource-operations"
$pathsToCheck[]="/vendor/sebastian/recursion-context"
$pathsToCheck[]="/vendor/sebastian/object-reflector"
$pathsToCheck[]="/vendor/sebastian/object-enumerator"
$pathsToCheck[]="/vendor/sebastian/global-state"
$pathsToCheck[]="/vendor/sebastian/exporter"
$pathsToCheck[]="/vendor/sebastian/environment"
$pathsToCheck[]="/vendor/sebastian/diff"
$pathsToCheck[]="/vendor/sebastian/comparator"
$pathsToCheck[]="/vendor/sebastian/code-unit-reverse-lookup"
$pathsToCheck[]="/vendor/sebastian/phpcpd"
$pathsToCheck[]="/vendor/sebastian/finder-facade"
$pathsToCheck[]="/vendor/doctrine/instantiator"
$pathsToCheck[]="/vendor/phpunit/php-text-template"
$pathsToCheck[]="/vendor/phpunit/phpunit-mock-objects"
$pathsToCheck[]="/vendor/phpunit/php-timer"
$pathsToCheck[]="/vendor/phpunit/phpunit"
$pathsToCheck[]="/vendor/phpunit/php-token-stream"
$pathsToCheck[]="/vendor/phpunit/php-file-iterator"
$pathsToCheck[]="/vendor/phpunit/php-code-coverage"
$pathsToCheck[]="/vendor/webmozart/assert"
$pathsToCheck[]="/vendor/phpdocumentor/reflection-common"
$pathsToCheck[]="/vendor/phpdocumentor/type-resolver"
$pathsToCheck[]="/vendor/phpdocumentor/reflection-docblock"
$pathsToCheck[]="/vendor/phpspec/prophecy"
$pathsToCheck[]="/vendor/phar-io/version"
$pathsToCheck[]="/vendor/phar-io/manifest"
$pathsToCheck[]="/vendor/myclabs/deep-copy"
$pathsToCheck[]="/vendor/pdepend/pdepend"
$pathsToCheck[]="/vendor/phpmd/phpmd"
$pathsToCheck[]="/vendor/ircmaxell/password-compat"
$pathsToCheck[]="/vendor/friendsofphp/php-cs-fixer"
$pathsToCheck[]="/vendor/edmondscommerce/magento2-data-migration"
$pathsToCheck[]="/vendor/edmondscommerce/magento2styleguide"
$pathsToCheck[]="/vendor/edmondscommerce/phpqa"
$pathsToCheck[]="/vendor/temando/module-shipping-m2"
$pathsToCheck[]="/vendor/dotmailer/dotmailer-magento2-extension"
$pathsToCheck[]="/vendor/phpstan/phpstan-shim"
$pathsToCheck[]="/vendor/jakub-onderka/php-parallel-lint"
$pathsToCheck[]="/vendor/jakub-onderka/php-console-color"
$pathsToCheck[]="/vendor/jakub-onderka/php-console-highlighter"
$pathsToCheck[]="/vendor/phploc/phploc"
$pathsToCheck[]="/vendor/johnkary/phpunit-speedtrap"